### PR TITLE
Limit boundary to panzoom contents

### PR DESCRIPTION
**Pull request by rbonomo**
Solves #105, kinda...

This solution works when:
minZoom: 1,
bounds: true,
boundsPadding: 1

### CODE REVIEW

**Comment by rbonomo** [comment]
Example using ```anvaka:master```
https://codepen.io/rbonomo/pen/QRaRBN

Example using ```rbonomo:support-full-bounds```
https://codepen.io/rbonomo/pen/VOQwWZ

**Comment by anvaka** [comment]
Ryan, appreciate this work. I'm just not happy with the API (and that's not your fault). The use of `bounds` along with `boundsPadding` seem to be a bit fragile (especially when `bounds` is defined as an object (not boolean).

I wonder if we could rethink the API of bounding boxes? What would be an elegant way to declare area where zoom/pan can happen?

My original version was preventing a scene from flying out of the view, but it looks like people want more. They want to define min/max zoom level, as well as bounding box of padding.

**Comment by axel-habermaier** [comment]
Works great for me so far. It is, however, important to mention that if panZoom is used with a canvas or image, browser tend to append extra space below the element. Make sure to add ``overflow: hidden;`` to the element's style to solve this problem and use ``:focus { outline: 0; }`` to disable the drawing of the focus box which might be distracting.

**Comment by anvaka** [comment]
@rbonomo I merged your change in so that your contribution is part of the git history for this project.

I'd still very hesitant to publish this as a new version because the API of the library seem very uhm... sloppy?

Need to think more about it.

**Comment by rbonomo** [comment]
@anvaka I will be giving this a think and will get back to you on the API change proposal.

**Pull request merged**
