### PR TITLE
Fix #26

### LINKED ISSUE #26: dispose() does not remove mouse wheel zoom
I'm using the npm package, 4.3.1 and when calling `instance.dispose()` only pan handlers are removed. I can still zoom with the mouse wheel.

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
Remove wheel event listener on correct domElement and not owner (parent element).

Fixes #26

### CODE REVIEW

**Comment by anvaka** [comment]
I looked a bit deeper into this, and slightly [reversed the logic](https://github.com/anvaka/panzoom/commit/bedcae6e37db650d6ecff85e7f7066bb3ed8ddd4#diff-50526c41fe46667ce7fa3a607c479e22R366) - instead of listening on the domElement, I listen on the owner now.

This is because if you have an `svg` like this:

```
<svg>
  <g id='scene'> </g>
</svg>
```

The scroll events wouldn't fire, unless we are listening on `svg` tag or hover over filled area of a `g` element. Hovering over a precise area is not very convenient, so I switched to listening on `svg`. 

Hope this doesn't break your use case!

**Comment by dotnetCarpenter** [comment]
No, not at all. I attach panzoom to my container element, but I can just attach it to an extra div inside the container, or whatever child element I have inside the container element.

I fact, my most pressing issue is that I'm not able to cancel events and/or can get the boundary option to work. I'm looking into implementing my own panzoom, since I can't see how I can hack your panzoom to fit my needs. This is not a critique of your code, just that there is too much for me to absorb into a mental model that I can retrofit to my use case.

**Comment by anvaka** [comment]
>  I'm not able to cancel events 

Interesting. Let me know if I can help. Feel free to ping me over email (anvaka@gmail.com) or, maybe elaborate a bit more here, what you are trying to do and what is broken?

**Comment by dotnetCarpenter** [comment]
I will upload my work, with your panzoom, tonight so you can have a look
and update this issue with specifics.

On Apr 11, 2018 6:39 AM, "Andrei Kashcha" <notifications@github.com> wrote:

I'm not able to cancel events

Interesting. Let me know if I can help. Feel free to ping me over email (
anvaka@gmail.com) or, maybe elaborate a bit more here, what you are trying
to do and what is broken?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/anvaka/panzoom/pull/27#issuecomment-380324835>, or mute
the thread

**Pull request merged**
